class CariDurumModel {
  CariDurumModel({
    this.BUGUNVADELIALACAKLARIMTL,
    this.BUGUNVADELIALACAKLARIMUSD,
    this.BUGUNVADELIALACAKLARIMEURO,
    this.BUGUNVADELIALACAKLARIMRLTOPLAM,
    this.BUGUNVADELIBORCLARIMTL,
    this.BUGUNVADELIBORCLARIMUSD,
    this.BUGUNVADELIBORCLARIMEURO,
    this.BUGUNVADELIBORCLARIMRLTOPLAM,
    this.TOPLAMALACAKLARIMTL,
    this.TOPLAMALACAKLARIMUSD,
    this.TOPLAMALACAKLARIMEURO,
    this.TOPLAMALACAKLARIMRLTOPLAM,
    this.TOPLAMBORCLARIMTL,
    this.TOPLAMBORCLARIMUSD,
    this.TOPLAMBORCLARIMEURO,
    this.TOPLAMBORCLARIMRLTOPLAM
  });
  double? BUGUNVADELIALACAKLARIMTL = 0.0;
  double? BUGUNVADELIALACAKLARIMUSD = 0.0;
  double? BUGUNVADELIALACAKLARIMEURO = 0.0;
  double? BUGUNVADELIALACAKLARIMRLTOPLAM = 0.0;

  double? BUGUNVADELIBORCLARIMTL = 0.0;
  double? BUGUNVADELIBORCLARIMUSD = 0.0;
  double? BUGUNVADELIBORCLARIMEURO = 0.0;
  double? BUGUNVADELIBORCLARIMRLTOPLAM = 0.0;

  double? TOPLAMALACAKLARIMTL = 0.0;
  double? TOPLAMALACAKLARIMUSD = 0.0;
  double? TOPLAMALACAKLARIMEURO = 0.0;
  double? TOPLAMALACAKLARIMRLTOPLAM = 0.0;

  double? TOPLAMBORCLARIMTL = 0.0;
  double? TOPLAMBORCLARIMUSD = 0.0;
  double? TOPLAMBORCLARIMEURO = 0.0;
  double? TOPLAMBORCLARIMRLTOPLAM = 0.0;
}
