class SiparisVeTekliflerModel {
  SiparisVeTekliflerModel({
    this.MUSTERISIPARISLER,
    this.SATINALMASIPARISLER,
    this.BEKLEYETEKLIFLER,
    this.ONAYDABEKLEYENMUSTERISIPARISLER,
    this.ONAYDABEKLEYENSATINALMASIPARISLER
  });
  double? MUSTERISIPARISLER = 0.0;
  double? SATINALMASIPARISLER = 0.0;
  double? BEKLEYETEKLIFLER = 0.0;
  double? ONAYDABEKLEYENMUSTERISIPARISLER = 0.0;
  double? ONAYDABEKLEYENSATINALMASIPARISLER = 0.0;

}
